export enum SCREENS {
    AUCTION = 'AUCTION',
    MYHUB = "MYHUB",
    SAVE = 'SAVE',
    BIDDIES = "BIDDIES",
    PROFILE = 'PROFILE',
    BIOMATRIC = 'BIOMATRIC',
    NOTIFICATION = 'NOTIFICATION',

}