export enum SCREENS {
    AUCTIONSTACK = 'AUCTIONSTACK',
    AUCTION = 'AUCTION',
    MYHUB = "MYHUB",
    SAVE = 'SAVE',
    BIDDIES = "BIDDIES",
    PROFILE = 'PROFILE',
    BIOMATRIC = 'BIOMATRIC',
    NOTIFICATION = 'NOTIFICATION',
    AUTH = "AUTH"
}